import { join } from 'path';
import {
  getShellRcFile,
  ensureDir,
  appendFile,
  readFile,
  fileExists,
  detectPlatform,
  isInteractive,
} from './utils.js';
import { installPowerShellAliases, isPowerShellIntegrationConfigured } from './powershell.js';

// Use npx directly - no local bin installation
const CCODEX_NPX_CMD = 'npx -y @tuannvm/ccodex';

/**
 * Generate alias content for Unix shells (zsh/bash)
 * Direct embedding into rc files - no separate alias file
 * All three functions are guarded to avoid conflicts with existing user definitions
 * Uses START/END markers for safe removal during updates
 */
function generateAliasesForRc(): string {
  return `

# >>> ccodex aliases START >>> # generated by npx @tuannvm/ccodex
if ! typeset -f ccodex >/dev/null 2>&1; then
  ccodex() {
    command ${CCODEX_NPX_CMD} "$@"
  }
fi

if ! typeset -f co >/dev/null 2>&1; then
  co() {
    command ${CCODEX_NPX_CMD} "$@"
  }
fi

if ! typeset -f claude-openai >/dev/null 2>&1; then
  claude-openai() {
    command ${CCODEX_NPX_CMD} "$@"
  }
fi
# <<< ccodex aliases END <<<
`;
}

/**
 * Check if ccodex block marker exists in content
 * Checks for our START marker to identify our alias block
 */
function hasCcodexBlock(content: string): boolean {
  return content.includes('# >>> ccodex aliases START >>>');
}

/**
 * Remove existing ccodex alias block from content
 * Finds and removes the entire block between START and END markers
 * Uses explicit markers to avoid deleting unrelated user content
 */
function removeCcodexBlock(content: string): string {
  // Match the entire ccodex alias block from START marker to END marker
  const blockRegex = /# >>> ccodex aliases START >>>[\s\S]*?# <<< ccodex aliases END <<<\n?/g;
  return content.replace(blockRegex, '').trimEnd();
}

/**
 * Add aliases to shell rc file
 * Creates file if needed, removes any existing ccodex blocks, then adds fresh aliases
 * This ensures idempotency - no duplicate blocks even if run multiple times
 */
async function addAliasesToRc(rcFile: string): Promise<void> {
  // Ensure rc file directory exists
  await ensureDir(join(rcFile, '..'));

  // Create rc file if it doesn't exist
  const fs = await import('fs/promises');
  try {
    await fs.writeFile(rcFile, '', { flag: 'wx' });
  } catch {
    // File exists, that's fine
  }

  let content = await readFile(rcFile);

  // Check if aliases already present
  if (hasCcodexBlock(content)) {
    // Remove existing block to prevent duplicates
    content = removeCcodexBlock(content);
    // Write back the cleaned content
    await fs.writeFile(rcFile, content + '\n', 'utf-8');
    console.log(`Cleaned existing ccodex aliases: ${rcFile}`);
  }

  // Append fresh aliases
  await appendFile(rcFile, generateAliasesForRc());
  console.log(`Added aliases to: ${rcFile}`);
}

/**
 * Configure shell integration
 * Adds aliases directly to rc files (no separate alias file)
 */
export async function configureShellIntegration(): Promise<void> {
  const platform = detectPlatform();

  // On Windows, use PowerShell
  if (platform.os === 'windows') {
    console.log('\nConfiguring PowerShell integration...');
    await installPowerShellAliases();
    console.log('PowerShell aliases installed. Restart PowerShell to use them.');
    return;
  }

  // Unix/macOS: use zsh/bash

  // Get the appropriate rc file
  const rcFile = getShellRcFile(platform);

  if (!isInteractive()) {
    // Non-interactive: auto-detect and add
    await addAliasesToRc(rcFile);
    return;
  }

  // Interactive: ask user
  // Determine default based on current shell
  const defaultChoice = platform.shell === 'bash' ? '2' : '1';
  const defaultName = platform.shell === 'bash' ? '~/.bashrc' : '~/.zshrc';

  console.log('\nChoose shell rc file for ccodex aliases:');
  console.log('  1) ~/.zshrc');
  console.log('  2) ~/.bashrc');
  console.log('  3) Both');
  console.log('  4) Skip (manual setup)');

  const readline = await import('readline');
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const choice = await new Promise<string>((resolve) => {
    rl.question(`Select [1-4] (default: ${defaultChoice}, detected: ${defaultName}): `, (answer) => {
      rl.close();
      resolve(answer || defaultChoice);
    });
  });

  const zshrc = join(platform.home, '.zshrc');
  const bashrc = join(platform.home, '.bashrc');

  switch (choice) {
    case '1':
      await addAliasesToRc(zshrc);
      break;
    case '2':
      await addAliasesToRc(bashrc);
      break;
    case '3':
      await addAliasesToRc(zshrc);
      await addAliasesToRc(bashrc);
      break;
    case '4':
      console.log('Skipped rc integration.');
      break;
    default:
      console.log('Invalid choice. Using ~/.zshrc');
      await addAliasesToRc(zshrc);
  }
}

/**
 * Check if shell integration is configured
 * Checks if rc file contains the aliases directly
 * Checks both .zshrc and .bashrc since user may have installed to either
 */
export async function isShellIntegrationConfigured(): Promise<boolean> {
  const platform = detectPlatform();

  // On Windows, check PowerShell integration
  if (platform.os === 'windows') {
    return await isPowerShellIntegrationConfigured();
  }

  // Check both possible rc files (user may have installed to either)
  const zshrc = join(platform.home, '.zshrc');
  const bashrc = join(platform.home, '.bashrc');

  for (const rcFile of [zshrc, bashrc]) {
    if (fileExists(rcFile)) {
      const content = await readFile(rcFile);
      if (hasCcodexBlock(content)) {
        return true;
      }
    }
  }

  return false;
}
