import { join } from 'path';
import {
  getShellRcFile,
  getAliasFile,
  ensureDir,
  writeFile,
  appendFile,
  readFile,
  fileExists,
  detectPlatform,
  isInteractive,
} from './utils.js';
import { installPowerShellAliases, isPowerShellIntegrationConfigured } from './powershell.js';

// Use npx directly - no local bin installation
const CCODEX_NPX_CMD = 'npx -y ccodex';

/**
 * Generate alias file content for Unix shells
 */
function generateAliasContent(): string {
  return `# ccodex aliases - generated by npx ccodex
ccodex() {
  command ${CCODEX_NPX_CMD} "$@"
}

if ! typeset -f co >/dev/null 2>&1; then
  co() {
    command ${CCODEX_NPX_CMD} "$@"
  }
fi

claude-openai() {
  command ${CCODEX_NPX_CMD} "$@"
}
`;
}

/**
 * Install alias file (Unix/macOS only)
 */
export async function installAliases(): Promise<void> {
  const platform = detectPlatform();

  // On Windows, use PowerShell aliases instead
  if (platform.os === 'windows') {
    await installPowerShellAliases();
    return;
  }

  const aliasFile = getAliasFile();
  await ensureDir(join(aliasFile, '..'));

  await writeFile(aliasFile, generateAliasContent());
  console.log(`Installed alias file: ${aliasFile}`);
}

/**
 * Check if alias file exists and is valid
 */
export async function hasAliasFile(): Promise<boolean> {
  const platform = detectPlatform();

  // On Windows, check PowerShell integration
  if (platform.os === 'windows') {
    return await isPowerShellIntegrationConfigured();
  }

  const aliasFile = getAliasFile();
  if (!fileExists(aliasFile)) {
    return false;
  }

  const content = await readFile(aliasFile);
  return (
    content.includes('ccodex()') &&
    content.includes('claude-openai()')
  );
}

/**
 * Generate source line for shell rc
 */
function generateSourceLine(aliasFile: string): string {
  return `[ -f "${aliasFile}" ] && source "${aliasFile}"`;
}

/**
 * Add source line to shell rc file
 */
async function addSourceToRc(rcFile: string): Promise<void> {
  const aliasFile = getAliasFile();

  // Create rc file if it doesn't exist
  const fs = await import('fs/promises');
  try {
    await fs.writeFile(rcFile, '', { flag: 'wx' });
  } catch {
    // File exists, that's fine
  }

  const content = await readFile(rcFile);

  // Check if already sourced
  if (content.includes(aliasFile)) {
    console.log(`Shell integration already present: ${rcFile}`);
    return;
  }

  const sourceLine = generateSourceLine(aliasFile);
  await appendFile(
    rcFile,
    `\n\n# ccodex aliases\n${sourceLine}\n`
  );
  console.log(`Added shell integration to: ${rcFile}`);
}

/**
 * Configure shell integration
 */
export async function configureShellIntegration(): Promise<void> {
  const platform = detectPlatform();

  // On Windows, use PowerShell
  if (platform.os === 'windows') {
    console.log('\nConfiguring PowerShell integration...');
    await installPowerShellAliases();
    console.log('PowerShell aliases installed. Restart PowerShell to use them.');
    return;
  }

  // Unix/macOS: use zsh/bash

  // Check if already configured (non-interactive check)
  const rcFile = getShellRcFile(platform);
  const aliasFile = getAliasFile();

  if (fileExists(rcFile)) {
    const content = await readFile(rcFile);
    if (content.includes(aliasFile)) {
      // Already configured, skip
      return;
    }
  }

  // Not configured, proceed with setup
  if (!isInteractive()) {
    // Non-interactive: auto-detect
    await addSourceToRc(rcFile);
    return;
  }

  // Interactive: ask user
  // Determine default based on current shell
  const defaultChoice = platform.shell === 'bash' ? '2' : '1';
  const defaultName = platform.shell === 'bash' ? '~/.bashrc' : '~/.zshrc';

  console.log('\nChoose shell rc file for ccodex aliases:');
  console.log('  1) ~/.zshrc');
  console.log('  2) ~/.bashrc');
  console.log('  3) Both');
  console.log('  4) Skip (manual source)');

  const readline = await import('readline');
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const choice = await new Promise<string>((resolve) => {
    rl.question(`Select [1-4] (default: ${defaultChoice}, detected: ${defaultName}): `, (answer) => {
      rl.close();
      resolve(answer || defaultChoice);
    });
  });

  const zshrc = join(platform.home, '.zshrc');
  const bashrc = join(platform.home, '.bashrc');

  switch (choice) {
    case '1':
      await addSourceToRc(zshrc);
      break;
    case '2':
      await addSourceToRc(bashrc);
      break;
    case '3':
      await addSourceToRc(zshrc);
      await addSourceToRc(bashrc);
      break;
    case '4':
      console.log('Skipped rc integration.');
      break;
    default:
      console.log('Invalid choice. Using ~/.zshrc');
      await addSourceToRc(zshrc);
  }
}

/**
 * Check if shell integration is configured
 */
export async function isShellIntegrationConfigured(): Promise<boolean> {
  const platform = detectPlatform();

  // On Windows, check PowerShell integration
  if (platform.os === 'windows') {
    return await isPowerShellIntegrationConfigured();
  }

  const rcFile = getShellRcFile(platform);

  if (!fileExists(rcFile)) {
    return false;
  }

  const content = await readFile(rcFile);
  const aliasFile = getAliasFile();
  return content.includes(aliasFile);
}
