/**
 * PowerShell-specific utilities for Windows support
 */

import { join } from 'path';
import { homedir } from 'os';
import { fileExists, ensureDir, appendFile, debugLog } from './utils.js';

// Use npx directly - no local bin installation
const CCODEX_NPX_CMD = 'npx -y ccodex';

/**
 * Get PowerShell profile path
 * Prefers PowerShell 7 (pwsh) profile, falls back to WindowsPowerShell
 */
export function getPowerShellProfilePath(): string | null {
  const home = homedir();

  // Try different PowerShell profile locations
  // Prefer PowerShell 7 profile, fall back to WindowsPowerShell
  const candidates = [
    join(home, 'Documents', 'PowerShell', 'Microsoft.PowerShell_profile.ps1'),  // PowerShell 7 (pwsh)
    join(home, 'Documents', 'WindowsPowerShell', 'Microsoft.PowerShell_profile.ps1'),  // WindowsPowerShell 5.x
  ];

  // If a profile file exists, use it
  for (const candidate of candidates) {
    if (fileExists(candidate)) {
      return candidate;
    }
  }

  // If using pwsh (PowerShell 7), default to its profile location
  // Check for pwsh by looking for the executable or PSModulePath pattern
  const isPwsh = process.env.PSModulePath?.includes('PowerShell') &&
                  !process.env.PSModulePath?.includes('WindowsPowerShell');

  if (isPwsh) {
    return candidates[0];  // PowerShell 7 profile
  }

  // Default to WindowsPowerShell path
  return candidates[1];
}

/**
 * Generate PowerShell alias content
 */
export async function generatePowerShellAlias(): Promise<string> {
  return `# ccodex aliases - generated by npx ccodex
function ccodex {
  npx -y ccodex $args
}

function co {
  npx -y ccodex $args
}

function claude-openai {
  npx -y ccodex $args
}
`;
}

/**
 * Install PowerShell aliases
 */
export async function installPowerShellAliases(): Promise<boolean> {
  const profilePath = getPowerShellProfilePath();
  if (!profilePath) {
    debugLog('Could not determine PowerShell profile path');
    return false;
  }

  // Ensure profile directory exists
  await ensureDir(join(profilePath, '..'));

  // Check if already configured with our aliases
  if (fileExists(profilePath)) {
    const content = await readFile(profilePath);
    // Check for all three expected functions to be present
    const hasCcodex = /\bccodex\s*\{[\s\S]*?npx -y ccodex/.test(content);
    const hasCo = /\bco\s*\{[\s\S]*?npx -y ccodex/.test(content);
    const hasClaudeOpenai = /\bclaude-openai\s*\{[\s\S]*?npx -y ccodex/.test(content);
    if (hasCcodex && hasCo && hasClaudeOpenai) {
      console.log('PowerShell aliases already installed');
      return true;
    }
  }

  // Append aliases to profile
  const aliasContent = await generatePowerShellAlias();
  await appendFile(profilePath, aliasContent);

  console.log(`Installed PowerShell aliases: ${profilePath}`);
  return true;
}

/**
 * Read file content (internal helper)
 */
async function readFile(path: string): Promise<string> {
  const fs = await import('fs/promises');
  return await fs.readFile(path, 'utf-8');
}

/**
 * Check if PowerShell integration is configured
 */
export async function isPowerShellIntegrationConfigured(): Promise<boolean> {
  const profilePath = getPowerShellProfilePath();
  if (!profilePath || !fileExists(profilePath)) {
    return false;
  }

  const content = await readFile(profilePath);
  // Check for all three expected functions with proper syntax
  const hasCcodex = /\bccodex\s*\{[\s\S]*?npx -y ccodex/.test(content);
  const hasCo = /\bco\s*\{[\s\S]*?npx -y ccodex/.test(content);
  const hasClaudeOpenai = /\bclaude-openai\s*\{[\s\S]*?npx -y ccodex/.test(content);
  return hasCcodex && hasCo && hasClaudeOpenai;
}
